import Head from "next/head";
import Image from "next/image";
// import { useSubgraph } from "../hooks/useSubgraph";
import { useMoralis } from "react-moralis";

export default function Home() {
  // const data = useSubgraph();
  const { authenticate, isAuthenticated, user } = useMoralis();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button className="bg-black" onClick={() => authenticate()}>
          Authenticate
        </button>
        <h1>Welcome {user?.get("username")}</h1>
      </div>
    </div>
  );
}
